//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sugestao_VO.Resources.ResourcesSugestao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesSugestaoEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesSugestaoEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sugestao_VO.Resources.ResourcesSugestao.ResourcesSugestaoEN", typeof(ResourcesSugestaoEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How.
        /// </summary>
        internal static string Sugestao_how {
            get {
                return ResourceManager.GetString("Sugestao_how", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Field How is required.
        /// </summary>
        internal static string Sugestao_how_Required {
            get {
                return ResourceManager.GetString("Sugestao_how_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Mutch.
        /// </summary>
        internal static string Sugestao_howmutch {
            get {
                return ResourceManager.GetString("Sugestao_howmutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Field How Mutch is required.
        /// </summary>
        internal static string Sugestao_howmutch_Required {
            get {
                return ResourceManager.GetString("Sugestao_howmutch_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Sugestão.
        /// </summary>
        internal static string Sugestao_idSugestao {
            get {
                return ResourceManager.GetString("Sugestao_idSugestao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Usuário.
        /// </summary>
        internal static string Sugestao_idUsuario {
            get {
                return ResourceManager.GetString("Sugestao_idUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencedor.
        /// </summary>
        internal static string Sugestao_vencedor {
            get {
                return ResourceManager.GetString("Sugestao_vencedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        internal static string Sugestao_what {
            get {
                return ResourceManager.GetString("Sugestao_what", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Field What is required.
        /// </summary>
        internal static string Sugestao_what_Required {
            get {
                return ResourceManager.GetString("Sugestao_what_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string Sugestao_when {
            get {
                return ResourceManager.GetString("Sugestao_when", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Field When is required.
        /// </summary>
        internal static string Sugestao_when_Required {
            get {
                return ResourceManager.GetString("Sugestao_when_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string Sugestao_where {
            get {
                return ResourceManager.GetString("Sugestao_where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Field Where is required.
        /// </summary>
        internal static string Sugestao_where_Required {
            get {
                return ResourceManager.GetString("Sugestao_where_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who.
        /// </summary>
        internal static string Sugestao_who {
            get {
                return ResourceManager.GetString("Sugestao_who", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Field Who is required.
        /// </summary>
        internal static string Sugestao_who_Required {
            get {
                return ResourceManager.GetString("Sugestao_who_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why.
        /// </summary>
        internal static string Sugestao_why {
            get {
                return ResourceManager.GetString("Sugestao_why", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Field Why is required.
        /// </summary>
        internal static string Sugestao_why_Required {
            get {
                return ResourceManager.GetString("Sugestao_why_Required", resourceCulture);
            }
        }
    }
}
