//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sugestao_VO.Resources.ResourcesUsuario {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesUsuarioES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesUsuarioES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sugestao_VO.Resources.ResourcesUsuario.ResourcesUsuarioES", typeof(ResourcesUsuarioES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string Usuario_cpf {
            get {
                return ResourceManager.GetString("Usuario_cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Campo CPF es obligatorio.
        /// </summary>
        internal static string Usuario_cpf_Required {
            get {
                return ResourceManager.GetString("Usuario_cpf_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Setor.
        /// </summary>
        internal static string Usuario_idSetor {
            get {
                return ResourceManager.GetString("Usuario_idSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Campo Sector es obligatorio.
        /// </summary>
        internal static string Usuario_idSetor_Required {
            get {
                return ResourceManager.GetString("Usuario_idSetor_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Usuario.
        /// </summary>
        internal static string Usuario_idUsuario {
            get {
                return ResourceManager.GetString("Usuario_idUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Usuario_nome {
            get {
                return ResourceManager.GetString("Usuario_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Campo Nombre es obligatorio.
        /// </summary>
        internal static string Usuario_nome_Required {
            get {
                return ResourceManager.GetString("Usuario_nome_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string Usuario_Senha {
            get {
                return ResourceManager.GetString("Usuario_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Campo Contraseña es obligatorio.
        /// </summary>
        internal static string Usuario_Senha_Required {
            get {
                return ResourceManager.GetString("Usuario_Senha_Required", resourceCulture);
            }
        }
    }
}
