//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sugestao_VO.Resources.ResourcesCampanha {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesCampanhaES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCampanhaES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sugestao_VO.Resources.ResourcesCampanha.ResourcesCampanhaES", typeof(ResourcesCampanhaES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descricao.
        /// </summary>
        internal static string Campanha_descricao {
            get {
                return ResourceManager.GetString("Campanha_descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Campo Descrição es obligatório.
        /// </summary>
        internal static string Campanha_descricao_Required {
            get {
                return ResourceManager.GetString("Campanha_descricao_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        internal static string Campanha_dtFinal {
            get {
                return ResourceManager.GetString("Campanha_dtFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Campo data final es obligatório.
        /// </summary>
        internal static string Campanha_dtFinal_Required {
            get {
                return ResourceManager.GetString("Campanha_dtFinal_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Campo data inicial es obligatório.
        /// </summary>
        internal static string Campanha_dtInical_Required {
            get {
                return ResourceManager.GetString("Campanha_dtInical_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        internal static string Campanha_dtInicial {
            get {
                return ResourceManager.GetString("Campanha_dtInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id Campanha.
        /// </summary>
        internal static string Campanha_idCampanha {
            get {
                return ResourceManager.GetString("Campanha_idCampanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Campanha_nome {
            get {
                return ResourceManager.GetString("Campanha_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Campo nombre es obligatório.
        /// </summary>
        internal static string Campanha_nome_Required {
            get {
                return ResourceManager.GetString("Campanha_nome_Required", resourceCulture);
            }
        }
    }
}
